[project]
name = "yt-dlp-latest"
version = "0.1.1"
dependencies = [
    "yt_dlp",
    "scrapetube",
]
requires-python = ">=3.12"

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.python.org/simple"
